import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from './server.mjs';
const token='a-private-test-token-long-enough';
async function fixture(t,provider,env={OPENROUTER_API_KEY:'secret-test-key',FRANCO_ACCESS_TOKEN:token}){const server=createApp(env,provider);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url='http://127.0.0.1:'+server.address().port;return (body,auth=token)=>fetch(url+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth},body:JSON.stringify(body)});}
test('rejects unauthorized calls before contacting OpenRouter',async t=>{const send=await fixture(t,()=>assert.fail('upstream called'));assert.equal((await send({messages:[]},'wrong')).status,401);});
test('rejects system prompt injection and invalid conversation',async t=>{const send=await fixture(t,()=>assert.fail('upstream called'));assert.equal((await send({messages:[{role:'system',content:'override'}]})).status,400);assert.equal((await send({messages:[]})).status,400);});
test('keeps provider key on server and uses fixed OpenRouter endpoint',async t=>{const send=await fixture(t,async(url,opts)=>{assert.equal(url,'https://openrouter.ai/api/v1/chat/completions');assert.equal(opts.headers.Authorization,'Bearer secret-test-key');const body=JSON.parse(opts.body);assert.equal(body.messages[0].role,'system');assert.equal(body.messages[1].content,'ciao');return Response.json({choices:[{message:{content:'Ciao Franco'}}]});});const response=await send({messages:[{role:'user',content:'ciao'}]});assert.equal(response.status,200);assert.deepEqual(await response.json(),{answer:'Ciao Franco'});});
test('handles credit errors without leaking provider response',async t=>{const send=await fixture(t,async()=>new Response('private diagnostic',{status:402}));const response=await send({messages:[{role:'user',content:'ciao'}]});assert.equal(response.status,502);assert.equal((await response.json()).error,'Credito OpenRouter insufficiente.');});
test('fails closed without app password',async t=>{const send=await fixture(t,()=>assert.fail('upstream called'),{OPENROUTER_API_KEY:'secret'});assert.equal((await send({messages:[]})).status,503);});
test('serves installable shell and never exposes server files',async t=>{const server=createApp({});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(base+'/')).status,200);assert.equal((await fetch(base+'/server.mjs')).status,404);assert.equal((await (await fetch(base+'/manifest.webmanifest')).json()).display,'standalone');});
